### ISSUE TITLE
Doubt on dimensions and sizes

### ISSUE THREAD

**Issue by beckmx** [gouldpa/Triple-Cycloidal-Robot-Arm-Proto-2#1]
Hello @gouldpa I was taking a look at your inventor design, I have a doubt, might be kinda dump, but I noticed that if I open the assambly in inventor 2019 the bearings of the middle gear seem to be out of boundaries, I exported the model to fusion360 and noticed the same dimension problem, I wonder if this only happens in the simulation process or is it related to a missing update?

awesome work!
<img width="454" alt="Screen Shot 2019-12-12 at 14 19 09" src="https://user-images.githubusercontent.com/456473/70746089-dcc45200-1cea-11ea-8023-e67480621cdd.png">
<img width="598" alt="Screen Shot 2019-12-12 at 14 15 00" src="https://user-images.githubusercontent.com/456473/70746090-dcc45200-1cea-11ea-8a7a-dda32edad35e.png">
<img width="437" alt="Screen Shot 2019-12-12 at 14 13 47" src="https://user-images.githubusercontent.com/456473/70746091-dcc45200-1cea-11ea-83b3-d7809889c264.png">

**Comment by gouldpa** [comment]
I have just checked the original file in Inventor. You are correct, it was missing an insert constraint. You can add the constraint yourself or I can do it if needed. 

I have moved on from this design for two reasons. Stepper motors have low torque and low speed for their size. The bearings are not held in place. Check out my new design https://www.thingiverse.com/thing:3888483 and https://www.youtube.com/watch?v=XWp5dkeHgTY

**Comment by beckmx** [comment]
I want to make both of your gearboxes :), I just got my brushless motors but while the magnetic sensors arrive I would like to try this assambly first, I noticed that it could be a great work if you use one of those new modules for stepper motors, very similar to the ones for brushless (ie [here closed loop stepper](https://www.aliexpress.com/item/33000387388.html?spm=a2g0s.9042311.0.0.6e5d63c0xZ0rGI)) but as I am no expert in inventor, if it is not much to ask, can you do the constraint, to keep learning a little bit more on my side

Greetings!

**Comment by gouldpa** [comment]
Sorry it took so long. Bearings and pins are fixed now.

**Comment by beckmx** [comment]
perfect timing, some of my bearings are arriving =D
